spring:
  application:
    name: centralmonitoring

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: metrics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # AI Provider Configuration
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

# MCP server configuration - will be configured programmatically
mcp:
  server:
    url: http://82.223.13.241:8000
    enabled: true

thanos:
  base-url: http://82.223.13.241:10904
  appid: my-app


server:
  port: 8081